### ISSUE TITLE
Remaining Tasks Automation Pipeline

### ISSUE THREAD

**Issue by Alvalunasan** [BrainCOGS/U19-pipeline_python#26]
@kabilar 

Almost all work in **u19_pipeline/automatic_job** directory

**class RecordingHandler()**: (processes done for a complete recording directory)
- _imaging_preingestion_:  ingest first tables of imaging element, execute SyncCode and insert recording process records.
- _electrophysiology_preingestion_: execute SyncCode

 
**class RecProcessHandler()**: (processes done for a recording process, (a probe, etc)
- _get_imaging_params_jobs_: Get params associated with each imaging job (as get_ephys_imaging_params_jobs)
For processing_paramset append *processing method* in paramset as in ephys_params with clustering_method
```
        # Get cluster param sets
        params_df = pd.DataFrame((ephys_pipeline.ephys_element.ClusteringParamSet.proj('params', 'clustering_method') * \
        recording_process.Processing.EphysParams.proj('paramset_idx') \
        & rec_process_keys).fetch(as_dict=True))
        params_df = params_df.drop('paramset_idx', axis=1)

        #Insert clustering method in params itself (for BrainCogsEphysSorters)
        params_df['params'] = params_df.apply(lambda x: {**x['params'], **{'clustering_method':x['clustering_method']}},axis=1)
```

- _ingest_element_: After processing ingest downstream tables for the element.

**Comment by kabilar** [comment]
> **class RecProcessHandler()**: (processes done for a recording process, (a probe, etc)
> 
> * _get_preprocess_params_: Get PreCluster & Cluster parameters for a given recording process

See https://github.com/BrainCOGS/U19-pipeline_python/pull/29.  Needs testing so submitted the pull request as a draft.

**Comment by kabilar** [comment]
Pending items
- Imaging functions
- ingest_element for populating ephys pipeline
